# Generated by Django 5.1.5 on 2025-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
